mutation REGISTER_USER($newUser: UserInput!) {
  registerUser(newUser: $newUser) {
    user {
      id
      email
      name
      createdAt
      updatedAt
    }
    token
  }
}

query AUTHENTICATE_USER($email: String!, $password: String!) {
  authenticateUser(email: $email, password: $password) {
    user {
      id
      email
      name
      createdAt
      updatedAt
    }
    token
  }
}

query AUTH_USER_PROFILE {
  authUserProfile {
    id
    name
    email
    createdAt
    updatedAt
  }
}

mutation CREATE_POST($post: PostInput!) {
  createPost(post: $post) {
    id
    title
    content
    featuredImgae
    createdAt
    updatedAt
    author {
      id
      email
      name
    }
  }
}

query GET_POSTS {
  getPosts {
    id
    title
    content
    featuredImgae
    createdAt
    updatedAt
    author {
      id
      email
      name
    }
  }
}

query GET_POST_BY_ID($postId: ID!) {
  getPostById(id: $postId) {
    id
    title
    content
    featuredImgae
    createdAt
    updatedAt
    author {
      id
      email
      name
    }
  }
}

mutation EDIT_POST_BY_ID($editPostId: ID!, $updatedPost: PostInput!) {
  editPostById(id: $editPostId, updatedPost: $updatedPost) {
    id
    title
    content
    featuredImgae
    createdAt
    updatedAt
  }
}

mutation DELETE_POST_BY_ID($deletePostById: ID!) {
  deletePostById(id: $deletePostById) {
    id
    message
    success
  }
}

mutation IMAGE_UPLOADER($file: Upload!) {
  imageUploader(file: $file)
}
